/**
 * Mots-clés par défaut pour les suggestions intelligentes de personas
 * Accessible depuis le main process et le renderer process
 */

export interface DefaultKeywordData {
  keyword: string;
  categories: string[];
  isDefault?: boolean;
}

/**
 * Keyword mapping par défaut (pour initialisation)
 * Catégories alignées avec PERSONA_CATEGORIES
 */
export const DEFAULT_KEYWORDS: Omit<DefaultKeywordData, 'id'>[] = [
  // Développement & Code
  { keyword: 'code', categories: ['Développement'], isDefault: true },
  { keyword: 'bug', categories: ['Développement'], isDefault: true },
  { keyword: 'erreur', categories: ['Développement'], isDefault: true },
  { keyword: 'debug', categories: ['Développement'], isDefault: true },
  { keyword: 'debugger', categories: ['Développement'], isDefault: true },
  { keyword: 'optimis', categories: ['Développement'], isDefault: true },
  { keyword: 'performance', categories: ['Développement'], isDefault: true },
  { keyword: 'test', categories: ['Développement'], isDefault: true },
  { keyword: 'fonction', categories: ['Développement'], isDefault: true },
  { keyword: 'algorithm', categories: ['Développement'], isDefault: true },
  { keyword: 'programme', categories: ['Développement'], isDefault: true },
  { keyword: 'développ', categories: ['Développement'], isDefault: true },
  { keyword: 'api', categories: ['Développement'], isDefault: true },
  { keyword: 'base de données', categories: ['Développement'], isDefault: true },
  { keyword: 'database', categories: ['Développement'], isDefault: true },
  { keyword: 'sql', categories: ['Développement'], isDefault: true },
  { keyword: 'backend', categories: ['Développement'], isDefault: true },
  { keyword: 'frontend', categories: ['Développement'], isDefault: true },
  { keyword: 'framework', categories: ['Développement'], isDefault: true },
  { keyword: 'librairie', categories: ['Développement'], isDefault: true },
  { keyword: 'library', categories: ['Développement'], isDefault: true },
  { keyword: 'package', categories: ['Développement'], isDefault: true },
  { keyword: 'module', categories: ['Développement'], isDefault: true },
  { keyword: 'class', categories: ['Développement'], isDefault: true },
  { keyword: 'méthode', categories: ['Développement'], isDefault: true },
  { keyword: 'variable', categories: ['Développement'], isDefault: true },
  { keyword: 'compile', categories: ['Développement'], isDefault: true },
  { keyword: 'build', categories: ['Développement'], isDefault: true },
  { keyword: 'deploy', categories: ['Développement'], isDefault: true },
  { keyword: 'git', categories: ['Développement'], isDefault: true },
  { keyword: 'version', categories: ['Développement'], isDefault: true },
  { keyword: 'docker', categories: ['Développement'], isDefault: true },
  { keyword: 'kubernetes', categories: ['Développement'], isDefault: true },
  { keyword: 'ci/cd', categories: ['Développement'], isDefault: true },
  { keyword: 'devops', categories: ['Développement'], isDefault: true },
  { keyword: 'serveur', categories: ['Développement'], isDefault: true },
  { keyword: 'server', categories: ['Développement'], isDefault: true },
  { keyword: 'cloud', categories: ['Développement'], isDefault: true },
  { keyword: 'aws', categories: ['Développement'], isDefault: true },
  { keyword: 'azure', categories: ['Développement'], isDefault: true },
  { keyword: 'infrastructure', categories: ['Développement'], isDefault: true },
  { keyword: 'architecture', categories: ['Développement'], isDefault: true },
  { keyword: 'microservice', categories: ['Développement'], isDefault: true },
  { keyword: 'rest', categories: ['Développement'], isDefault: true },
  { keyword: 'graphql', categories: ['Développement'], isDefault: true },
  { keyword: 'websocket', categories: ['Développement'], isDefault: true },
  { keyword: 'authentification', categories: ['Développement'], isDefault: true },
  { keyword: 'sécurité', categories: ['Développement'], isDefault: true },
  { keyword: 'encrypt', categories: ['Développement'], isDefault: true },
  { keyword: 'hash', categories: ['Développement'], isDefault: true },
  { keyword: 'token', categories: ['Développement'], isDefault: true },
  { keyword: 'session', categories: ['Développement'], isDefault: true },
  { keyword: 'cookie', categories: ['Développement'], isDefault: true },
  { keyword: 'cors', categories: ['Développement'], isDefault: true },
  { keyword: 'middleware', categories: ['Développement'], isDefault: true },
  { keyword: 'route', categories: ['Développement'], isDefault: true },
  { keyword: 'endpoint', categories: ['Développement'], isDefault: true },
  { keyword: 'request', categories: ['Développement'], isDefault: true },
  { keyword: 'response', categories: ['Développement'], isDefault: true },
  { keyword: 'http', categories: ['Développement'], isDefault: true },
  { keyword: 'https', categories: ['Développement'], isDefault: true },
  { keyword: 'json', categories: ['Développement'], isDefault: true },
  { keyword: 'xml', categories: ['Développement'], isDefault: true },
  { keyword: 'yaml', categories: ['Développement'], isDefault: true },
  { keyword: 'config', categories: ['Développement'], isDefault: true },
  { keyword: 'environment', categories: ['Développement'], isDefault: true },
  { keyword: 'log', categories: ['Développement'], isDefault: true },
  { keyword: 'monitoring', categories: ['Développement'], isDefault: true },
  { keyword: 'trace', categories: ['Développement'], isDefault: true },

  // Créatif
  { keyword: 'créat', categories: ['Créatif'], isDefault: true },
  { keyword: 'créer', categories: ['Créatif'], isDefault: true },
  { keyword: 'design', categories: ['Créatif'], isDefault: true },
  { keyword: 'idée', categories: ['Créatif'], isDefault: true },
  { keyword: 'innov', categories: ['Créatif'], isDefault: true },
  { keyword: 'imagine', categories: ['Créatif'], isDefault: true },
  { keyword: 'histoire', categories: ['Créatif'], isDefault: true },
  { keyword: 'story', categories: ['Créatif'], isDefault: true },
  { keyword: 'narrat', categories: ['Créatif'], isDefault: true },
  { keyword: 'personnage', categories: ['Créatif'], isDefault: true },
  { keyword: 'scénario', categories: ['Créatif'], isDefault: true },
  { keyword: 'script', categories: ['Créatif'], isDefault: true },
  { keyword: 'dialogue', categories: ['Créatif'], isDefault: true },
  { keyword: 'fiction', categories: ['Créatif'], isDefault: true },
  { keyword: 'fantaisie', categories: ['Créatif'], isDefault: true },
  { keyword: 'fantasy', categories: ['Créatif'], isDefault: true },
  { keyword: 'science-fiction', categories: ['Créatif'], isDefault: true },
  { keyword: 'roman', categories: ['Créatif'], isDefault: true },
  { keyword: 'poème', categories: ['Créatif'], isDefault: true },
  { keyword: 'poésie', categories: ['Créatif'], isDefault: true },
  { keyword: 'chanson', categories: ['Créatif'], isDefault: true },
  { keyword: 'musique', categories: ['Créatif'], isDefault: true },
  { keyword: 'artistique', categories: ['Créatif'], isDefault: true },
  { keyword: 'visuel', categories: ['Créatif'], isDefault: true },
  { keyword: 'graphique', categories: ['Créatif'], isDefault: true },
  { keyword: 'logo', categories: ['Créatif'], isDefault: true },
  { keyword: 'branding', categories: ['Créatif'], isDefault: true },
  { keyword: 'concept', categories: ['Créatif'], isDefault: true },
  { keyword: 'brainstorm', categories: ['Créatif'], isDefault: true },
  { keyword: 'inspiration', categories: ['Créatif'], isDefault: true },
  { keyword: 'original', categories: ['Créatif'], isDefault: true },
  { keyword: 'unique', categories: ['Créatif'], isDefault: true },
  { keyword: 'inventif', categories: ['Créatif'], isDefault: true },
  { keyword: 'couleur', categories: ['Créatif'], isDefault: true },
  { keyword: 'palette', categories: ['Créatif'], isDefault: true },
  { keyword: 'style', categories: ['Créatif'], isDefault: true },
  { keyword: 'thème', categories: ['Créatif'], isDefault: true },
  { keyword: 'mood', categories: ['Créatif'], isDefault: true },
  { keyword: 'ambiance', categories: ['Créatif'], isDefault: true },

  // Analyse & Stratégie
  { keyword: 'analys', categories: ['Analyse'], isDefault: true },
  { keyword: 'stratég', categories: ['Analyse', 'Business'], isDefault: true },
  { keyword: 'décision', categories: ['Analyse', 'Business'], isDefault: true },
  { keyword: 'données', categories: ['Analyse'], isDefault: true },
  { keyword: 'data', categories: ['Analyse'], isDefault: true },
  { keyword: 'statistique', categories: ['Analyse'], isDefault: true },
  { keyword: 'metrics', categories: ['Analyse'], isDefault: true },
  { keyword: 'kpi', categories: ['Analyse', 'Business'], isDefault: true },
  { keyword: 'rapport', categories: ['Analyse'], isDefault: true },
  { keyword: 'report', categories: ['Analyse'], isDefault: true },
  { keyword: 'tableau', categories: ['Analyse'], isDefault: true },
  { keyword: 'dashboard', categories: ['Analyse'], isDefault: true },
  { keyword: 'visualisation', categories: ['Analyse'], isDefault: true },
  { keyword: 'graphe', categories: ['Analyse'], isDefault: true },
  { keyword: 'chart', categories: ['Analyse'], isDefault: true },
  { keyword: 'tendance', categories: ['Analyse'], isDefault: true },
  { keyword: 'trend', categories: ['Analyse'], isDefault: true },
  { keyword: 'prédiction', categories: ['Analyse'], isDefault: true },
  { keyword: 'forecast', categories: ['Analyse'], isDefault: true },
  { keyword: 'modèle', categories: ['Analyse'], isDefault: true },
  { keyword: 'machine learning', categories: ['Analyse', 'Développement'], isDefault: true },
  { keyword: 'intelligence artificielle', categories: ['Analyse', 'Développement'], isDefault: true },
  { keyword: 'ai', categories: ['Analyse', 'Développement'], isDefault: true },
  { keyword: 'deep learning', categories: ['Analyse', 'Développement'], isDefault: true },
  { keyword: 'neural', categories: ['Analyse', 'Développement'], isDefault: true },
  { keyword: 'dataset', categories: ['Analyse'], isDefault: true },
  { keyword: 'training', categories: ['Analyse'], isDefault: true },
  { keyword: 'évaluation', categories: ['Analyse'], isDefault: true },
  { keyword: 'benchmark', categories: ['Analyse'], isDefault: true },
  { keyword: 'compara', categories: ['Analyse'], isDefault: true },
  { keyword: 'audit', categories: ['Analyse'], isDefault: true },
  { keyword: 'diagnostic', categories: ['Analyse'], isDefault: true },
  { keyword: 'étude', categories: ['Analyse'], isDefault: true },
  { keyword: 'recherche', categories: ['Analyse', 'Science'], isDefault: true },
  { keyword: 'investigation', categories: ['Analyse'], isDefault: true },
  { keyword: 'enquête', categories: ['Analyse'], isDefault: true },
  { keyword: 'sondage', categories: ['Analyse'], isDefault: true },
  { keyword: 'questionnaire', categories: ['Analyse'], isDefault: true },
  { keyword: 'survey', categories: ['Analyse'], isDefault: true },

  // Éducation
  { keyword: 'expliqu', categories: ['Enseignement'], isDefault: true },
  { keyword: 'apprend', categories: ['Enseignement'], isDefault: true },
  { keyword: 'enseign', categories: ['Enseignement'], isDefault: true },
  { keyword: 'comment', categories: ['Enseignement'], isDefault: true },
  { keyword: 'tutoriel', categories: ['Enseignement'], isDefault: true },
  { keyword: 'cours', categories: ['Enseignement'], isDefault: true },
  { keyword: 'leçon', categories: ['Enseignement'], isDefault: true },
  { keyword: 'formation', categories: ['Enseignement'], isDefault: true },
  { keyword: 'éducat', categories: ['Enseignement'], isDefault: true },
  { keyword: 'pédagog', categories: ['Enseignement'], isDefault: true },
  { keyword: 'guide', categories: ['Enseignement'], isDefault: true },
  { keyword: 'introduction', categories: ['Enseignement'], isDefault: true },
  { keyword: 'débutant', categories: ['Enseignement'], isDefault: true },
  { keyword: 'initiation', categories: ['Enseignement'], isDefault: true },
  { keyword: 'comprendre', categories: ['Enseignement'], isDefault: true },
  { keyword: 'connaiss', categories: ['Enseignement'], isDefault: true },
  { keyword: 'savoir', categories: ['Enseignement'], isDefault: true },
  { keyword: 'théorie', categories: ['Enseignement'], isDefault: true },
  { keyword: 'pratique', categories: ['Enseignement'], isDefault: true },
  { keyword: 'exercice', categories: ['Enseignement'], isDefault: true },
  { keyword: 'exemple', categories: ['Enseignement'], isDefault: true },
  { keyword: 'démo', categories: ['Enseignement'], isDefault: true },
  { keyword: 'illustr', categories: ['Enseignement'], isDefault: true },
  { keyword: 'clarifi', categories: ['Enseignement'], isDefault: true },
  { keyword: 'simplifie', categories: ['Enseignement'], isDefault: true },
  { keyword: 'vulgarise', categories: ['Enseignement'], isDefault: true },
  { keyword: 'pas à pas', categories: ['Enseignement'], isDefault: true },
  { keyword: 'étape', categories: ['Enseignement'], isDefault: true },
  { keyword: 'instruction', categories: ['Enseignement'], isDefault: true },
  { keyword: 'manuel', categories: ['Enseignement'], isDefault: true },
  { keyword: 'handbook', categories: ['Enseignement'], isDefault: true },

  // Écriture & Rédaction
  { keyword: 'écri', categories: ['Écriture'], isDefault: true },
  { keyword: 'rédige', categories: ['Écriture'], isDefault: true },
  { keyword: 'article', categories: ['Écriture'], isDefault: true },
  { keyword: 'document', categories: ['Écriture'], isDefault: true },
  { keyword: 'texte', categories: ['Écriture'], isDefault: true },
  { keyword: 'contenu', categories: ['Écriture'], isDefault: true },
  { keyword: 'content', categories: ['Écriture'], isDefault: true },
  { keyword: 'blog', categories: ['Écriture'], isDefault: true },
  { keyword: 'post', categories: ['Écriture'], isDefault: true },
  { keyword: 'publication', categories: ['Écriture'], isDefault: true },
  { keyword: 'essai', categories: ['Écriture'], isDefault: true },
  { keyword: 'mémoire', categories: ['Écriture'], isDefault: true },
  { keyword: 'thèse', categories: ['Écriture'], isDefault: true },
  { keyword: 'dissertation', categories: ['Écriture'], isDefault: true },
  { keyword: 'résumé', categories: ['Écriture'], isDefault: true },
  { keyword: 'synthèse', categories: ['Écriture'], isDefault: true },
  { keyword: 'abstract', categories: ['Écriture'], isDefault: true },
  { keyword: 'conclusion', categories: ['Écriture'], isDefault: true },
  { keyword: 'paragraphe', categories: ['Écriture'], isDefault: true },
  { keyword: 'phrase', categories: ['Écriture'], isDefault: true },
  { keyword: 'reformule', categories: ['Écriture'], isDefault: true },
  { keyword: 'paraphrase', categories: ['Écriture'], isDefault: true },
  { keyword: 'révise', categories: ['Écriture'], isDefault: true },
  { keyword: 'corrige', categories: ['Écriture'], isDefault: true },
  { keyword: 'améliore', categories: ['Écriture'], isDefault: true },
  { keyword: 'grammaire', categories: ['Écriture'], isDefault: true },
  { keyword: 'orthographe', categories: ['Écriture'], isDefault: true },
  { keyword: 'syntaxe', categories: ['Écriture'], isDefault: true },
  { keyword: 'ponctuation', categories: ['Écriture'], isDefault: true },
  { keyword: 'ton', categories: ['Écriture'], isDefault: true },
  { keyword: 'voix', categories: ['Écriture'], isDefault: true },
  { keyword: 'formel', categories: ['Écriture'], isDefault: true },
  { keyword: 'informel', categories: ['Écriture'], isDefault: true },
  { keyword: 'professionnel', categories: ['Écriture'], isDefault: true },
  { keyword: 'académique', categories: ['Écriture'], isDefault: true },

  // Communication & Marketing
  { keyword: 'communiqu', categories: ['Marketing'], isDefault: true },
  { keyword: 'marketing', categories: ['Marketing'], isDefault: true },
  { keyword: 'publicité', categories: ['Marketing'], isDefault: true },
  { keyword: 'promotion', categories: ['Marketing'], isDefault: true },
  { keyword: 'campagne', categories: ['Marketing'], isDefault: true },
  { keyword: 'slogan', categories: ['Marketing'], isDefault: true },
  { keyword: 'message', categories: ['Marketing'], isDefault: true },
  { keyword: 'audience', categories: ['Marketing'], isDefault: true },
  { keyword: 'cible', categories: ['Marketing'], isDefault: true },
  { keyword: 'target', categories: ['Marketing'], isDefault: true },
  { keyword: 'client', categories: ['Marketing', 'Business'], isDefault: true },
  { keyword: 'prospect', categories: ['Marketing', 'Business'], isDefault: true },
  { keyword: 'lead', categories: ['Marketing', 'Business'], isDefault: true },
  { keyword: 'conversion', categories: ['Marketing'], isDefault: true },
  { keyword: 'engagement', categories: ['Marketing'], isDefault: true },
  { keyword: 'social media', categories: ['Marketing'], isDefault: true },
  { keyword: 'réseaux sociaux', categories: ['Marketing'], isDefault: true },
  { keyword: 'facebook', categories: ['Marketing'], isDefault: true },
  { keyword: 'instagram', categories: ['Marketing'], isDefault: true },
  { keyword: 'twitter', categories: ['Marketing'], isDefault: true },
  { keyword: 'linkedin', categories: ['Marketing'], isDefault: true },
  { keyword: 'tiktok', categories: ['Marketing'], isDefault: true },
  { keyword: 'youtube', categories: ['Marketing'], isDefault: true },
  { keyword: 'email', categories: ['Marketing'], isDefault: true },
  { keyword: 'newsletter', categories: ['Marketing'], isDefault: true },
  { keyword: 'seo', categories: ['Marketing'], isDefault: true },
  { keyword: 'référencement', categories: ['Marketing'], isDefault: true },
  { keyword: 'sem', categories: ['Marketing'], isDefault: true },
  { keyword: 'ads', categories: ['Marketing'], isDefault: true },
  { keyword: 'google ads', categories: ['Marketing'], isDefault: true },
  { keyword: 'landing page', categories: ['Marketing'], isDefault: true },
  { keyword: 'call to action', categories: ['Marketing'], isDefault: true },
  { keyword: 'cta', categories: ['Marketing'], isDefault: true },
  { keyword: 'marque', categories: ['Marketing'], isDefault: true },
  { keyword: 'identité', categories: ['Marketing'], isDefault: true },
  { keyword: 'positionnement', categories: ['Marketing'], isDefault: true },
  { keyword: 'notoriété', categories: ['Marketing'], isDefault: true },
  { keyword: 'visibilité', categories: ['Marketing'], isDefault: true },
  { keyword: 'reach', categories: ['Marketing'], isDefault: true },
  { keyword: 'impression', categories: ['Marketing'], isDefault: true },
  { keyword: 'clic', categories: ['Marketing'], isDefault: true },
  { keyword: 'trafic', categories: ['Marketing'], isDefault: true },

  // Business
  { keyword: 'business', categories: ['Business'], isDefault: true },
  { keyword: 'entreprise', categories: ['Business'], isDefault: true },
  { keyword: 'société', categories: ['Business'], isDefault: true },
  { keyword: 'startup', categories: ['Business'], isDefault: true },
  { keyword: 'entrepreneur', categories: ['Business'], isDefault: true },
  { keyword: 'plan d\'affaires', categories: ['Business'], isDefault: true },
  { keyword: 'business plan', categories: ['Business'], isDefault: true },
  { keyword: 'modèle économique', categories: ['Business'], isDefault: true },
  { keyword: 'business model', categories: ['Business'], isDefault: true },
  { keyword: 'revenue', categories: ['Business'], isDefault: true },
  { keyword: 'profit', categories: ['Business'], isDefault: true },
  { keyword: 'rentabilité', categories: ['Business'], isDefault: true },
  { keyword: 'croissance', categories: ['Business'], isDefault: true },
  { keyword: 'growth', categories: ['Business'], isDefault: true },
  { keyword: 'scale', categories: ['Business'], isDefault: true },
  { keyword: 'investissement', categories: ['Business'], isDefault: true },
  { keyword: 'financement', categories: ['Business'], isDefault: true },
  { keyword: 'levée de fonds', categories: ['Business'], isDefault: true },
  { keyword: 'funding', categories: ['Business'], isDefault: true },
  { keyword: 'pitch', categories: ['Business'], isDefault: true },
  { keyword: 'présentation', categories: ['Business'], isDefault: true },
  { keyword: 'deck', categories: ['Business'], isDefault: true },
  { keyword: 'budget', categories: ['Business'], isDefault: true },
  { keyword: 'finance', categories: ['Business'], isDefault: true },
  { keyword: 'comptabilité', categories: ['Business'], isDefault: true },
  { keyword: 'accounting', categories: ['Business'], isDefault: true },
  { keyword: 'ressources humaines', categories: ['Business'], isDefault: true },
  { keyword: 'rh', categories: ['Business'], isDefault: true },
  { keyword: 'hr', categories: ['Business'], isDefault: true },
  { keyword: 'recrutement', categories: ['Business'], isDefault: true },
  { keyword: 'hiring', categories: ['Business'], isDefault: true },
  { keyword: 'management', categories: ['Business'], isDefault: true },
  { keyword: 'gestion', categories: ['Business'], isDefault: true },
  { keyword: 'leadership', categories: ['Business'], isDefault: true },
  { keyword: 'équipe', categories: ['Business'], isDefault: true },
  { keyword: 'team', categories: ['Business'], isDefault: true },
  { keyword: 'organisation', categories: ['Business'], isDefault: true },
  { keyword: 'process', categories: ['Business'], isDefault: true },
  { keyword: 'workflow', categories: ['Business'], isDefault: true },
  { keyword: 'productivité', categories: ['Business'], isDefault: true },
  { keyword: 'efficacité', categories: ['Business'], isDefault: true },
  { keyword: 'objectif', categories: ['Business'], isDefault: true },
  { keyword: 'goal', categories: ['Business'], isDefault: true },
  { keyword: 'okr', categories: ['Business'], isDefault: true },
  { keyword: 'roadmap', categories: ['Business'], isDefault: true },
  { keyword: 'planning', categories: ['Business'], isDefault: true },

  // Science
  { keyword: 'scientifique', categories: ['Science'], isDefault: true },
  { keyword: 'science', categories: ['Science'], isDefault: true },
  { keyword: 'expérience', categories: ['Science'], isDefault: true },
  { keyword: 'experiment', categories: ['Science'], isDefault: true },
  { keyword: 'hypothèse', categories: ['Science'], isDefault: true },
  { keyword: 'théorie', categories: ['Science'], isDefault: true },
  { keyword: 'loi', categories: ['Science'], isDefault: true },
  { keyword: 'formule', categories: ['Science'], isDefault: true },
  { keyword: 'équation', categories: ['Science'], isDefault: true },
  { keyword: 'mathématique', categories: ['Science'], isDefault: true },
  { keyword: 'math', categories: ['Science'], isDefault: true },
  { keyword: 'calcul', categories: ['Science'], isDefault: true },
  { keyword: 'physique', categories: ['Science'], isDefault: true },
  { keyword: 'chimie', categories: ['Science'], isDefault: true },
  { keyword: 'biologie', categories: ['Science'], isDefault: true },
  { keyword: 'médecine', categories: ['Science'], isDefault: true },
  { keyword: 'santé', categories: ['Science'], isDefault: true },
  { keyword: 'anatomie', categories: ['Science'], isDefault: true },
  { keyword: 'génétique', categories: ['Science'], isDefault: true },
  { keyword: 'adn', categories: ['Science'], isDefault: true },
  { keyword: 'cellule', categories: ['Science'], isDefault: true },
  { keyword: 'molécule', categories: ['Science'], isDefault: true },
  { keyword: 'atome', categories: ['Science'], isDefault: true },
  { keyword: 'énergie', categories: ['Science'], isDefault: true },
  { keyword: 'force', categories: ['Science'], isDefault: true },
  { keyword: 'mouvement', categories: ['Science'], isDefault: true },
  { keyword: 'vitesse', categories: ['Science'], isDefault: true },
  { keyword: 'température', categories: ['Science'], isDefault: true },
  { keyword: 'pression', categories: ['Science'], isDefault: true },
  { keyword: 'volume', categories: ['Science'], isDefault: true },
  { keyword: 'masse', categories: ['Science'], isDefault: true },
  { keyword: 'densité', categories: ['Science'], isDefault: true },
  { keyword: 'réaction', categories: ['Science'], isDefault: true },
  { keyword: 'élément', categories: ['Science'], isDefault: true },
  { keyword: 'composé', categories: ['Science'], isDefault: true },
  { keyword: 'laboratoire', categories: ['Science'], isDefault: true },
  { keyword: 'lab', categories: ['Science'], isDefault: true },
  { keyword: 'microscope', categories: ['Science'], isDefault: true },
  { keyword: 'observation', categories: ['Science'], isDefault: true },
  { keyword: 'mesure', categories: ['Science'], isDefault: true },
];
